### ISSUE TITLE
prometheus statefulset start failed for secret not found

### ISSUE THREAD

**Issue by like-inspur** [huxos/prometheus-kubernetes#1]
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              4m                 default-scheduler  Successfully assigned prometheus-k8s-0 to node1
  Normal   SuccessfulMountVolume  4m                 kubelet, node1     MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  4m                 kubelet, node1     MountVolume.SetUp succeeded for volume "rules"
  Normal   SuccessfulMountVolume  4m                 kubelet, node1     MountVolume.SetUp succeeded for volume "prometheus-k8s-token-qxq5l"
  Warning  FailedMount            16s (x10 over 4m)  kubelet, node1     MountVolume.SetUp failed for volume "etc-etcd-ssl" : secrets "etcd-client-ssl" not found
  Warning  FailedMount            7s (x2 over 2m)    kubelet, node1     Unable to mount volumes for pod "prometheus-k8s-0_monitoring(3723240c-cb71-11e7-9922-005056b613fe)": timeout expired waiting for volumes to attach/mount for pod "monitoring"/"prometheus-k8s-0". list of unattached/unmounted volumes=[etc-etcd-ssl]
  Warning  FailedSync             7s (x2 over 2m)    kubelet, node1     Error syncing pod

**Comment by huxos** [comment]
fixed it. just delete  the volume etc-etcd-ssl
